
package com.tsp.zone;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b20 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ZoneManagerPortType", targetNamespace = "http://zone.tsp.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ZoneManagerPortType {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doAddMember", targetNamespace = "http://zone.tsp.com", className = "com.tsp.zone.DoAddMember")
    @ResponseWrapper(localName = "doAddMemberResponse", targetNamespace = "http://zone.tsp.com", className = "com.tsp.zone.DoAddMemberResponse")
    @Action(input = "http://zone.tsp.com/ZoneManagerPortType/doAddMemberRequest", output = "http://zone.tsp.com/ZoneManagerPortType/doAddMemberResponse")
    public int doAddMember(
        @WebParam(name = "arg0", targetNamespace = "")
        List<String> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<Object> arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doCheckMember", targetNamespace = "http://zone.tsp.com", className = "com.tsp.zone.DoCheckMember")
    @ResponseWrapper(localName = "doCheckMemberResponse", targetNamespace = "http://zone.tsp.com", className = "com.tsp.zone.DoCheckMemberResponse")
    @Action(input = "http://zone.tsp.com/ZoneManagerPortType/doCheckMemberRequest", output = "http://zone.tsp.com/ZoneManagerPortType/doCheckMemberResponse")
    public boolean doCheckMember(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "doAddBilling", targetNamespace = "http://zone.tsp.com", className = "com.tsp.zone.DoAddBilling")
    @ResponseWrapper(localName = "doAddBillingResponse", targetNamespace = "http://zone.tsp.com", className = "com.tsp.zone.DoAddBillingResponse")
    @Action(input = "http://zone.tsp.com/ZoneManagerPortType/doAddBillingRequest", output = "http://zone.tsp.com/ZoneManagerPortType/doAddBillingResponse")
    public void doAddBilling(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<String> arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        List<Object> arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doCheckBilling", targetNamespace = "http://zone.tsp.com", className = "com.tsp.zone.DoCheckBilling")
    @ResponseWrapper(localName = "doCheckBillingResponse", targetNamespace = "http://zone.tsp.com", className = "com.tsp.zone.DoCheckBillingResponse")
    @Action(input = "http://zone.tsp.com/ZoneManagerPortType/doCheckBillingRequest", output = "http://zone.tsp.com/ZoneManagerPortType/doCheckBillingResponse")
    public boolean doCheckBilling(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "doAddClient", targetNamespace = "http://zone.tsp.com", className = "com.tsp.zone.DoAddClient")
    @ResponseWrapper(localName = "doAddClientResponse", targetNamespace = "http://zone.tsp.com", className = "com.tsp.zone.DoAddClientResponse")
    @Action(input = "http://zone.tsp.com/ZoneManagerPortType/doAddClientRequest", output = "http://zone.tsp.com/ZoneManagerPortType/doAddClientResponse")
    public void doAddClient(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<String> arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        List<String> arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doListMember", targetNamespace = "http://zone.tsp.com", className = "com.tsp.zone.DoListMember")
    @ResponseWrapper(localName = "doListMemberResponse", targetNamespace = "http://zone.tsp.com", className = "com.tsp.zone.DoListMemberResponse")
    @Action(input = "http://zone.tsp.com/ZoneManagerPortType/doListMemberRequest", output = "http://zone.tsp.com/ZoneManagerPortType/doListMemberResponse")
    public List<String> doListMember();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.tsp.zone.MemberState
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doGetMemberProfile", targetNamespace = "http://zone.tsp.com", className = "com.tsp.zone.DoGetMemberProfile")
    @ResponseWrapper(localName = "doGetMemberProfileResponse", targetNamespace = "http://zone.tsp.com", className = "com.tsp.zone.DoGetMemberProfileResponse")
    @Action(input = "http://zone.tsp.com/ZoneManagerPortType/doGetMemberProfileRequest", output = "http://zone.tsp.com/ZoneManagerPortType/doGetMemberProfileResponse")
    public MemberState doGetMemberProfile(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.tsp.zone.BillingState
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doGetMemberBilling", targetNamespace = "http://zone.tsp.com", className = "com.tsp.zone.DoGetMemberBilling")
    @ResponseWrapper(localName = "doGetMemberBillingResponse", targetNamespace = "http://zone.tsp.com", className = "com.tsp.zone.DoGetMemberBillingResponse")
    @Action(input = "http://zone.tsp.com/ZoneManagerPortType/doGetMemberBillingRequest", output = "http://zone.tsp.com/ZoneManagerPortType/doGetMemberBillingResponse")
    public BillingState doGetMemberBilling(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doGetMemberAccount", targetNamespace = "http://zone.tsp.com", className = "com.tsp.zone.DoGetMemberAccount")
    @ResponseWrapper(localName = "doGetMemberAccountResponse", targetNamespace = "http://zone.tsp.com", className = "com.tsp.zone.DoGetMemberAccountResponse")
    @Action(input = "http://zone.tsp.com/ZoneManagerPortType/doGetMemberAccountRequest", output = "http://zone.tsp.com/ZoneManagerPortType/doGetMemberAccountResponse")
    public List<String> doGetMemberAccount(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doLogin", targetNamespace = "http://zone.tsp.com", className = "com.tsp.zone.DoLogin")
    @ResponseWrapper(localName = "doLoginResponse", targetNamespace = "http://zone.tsp.com", className = "com.tsp.zone.DoLoginResponse")
    @Action(input = "http://zone.tsp.com/ZoneManagerPortType/doLoginRequest", output = "http://zone.tsp.com/ZoneManagerPortType/doLoginResponse")
    public int doLogin(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "doAddCarrier", targetNamespace = "http://zone.tsp.com", className = "com.tsp.zone.DoAddCarrier")
    @ResponseWrapper(localName = "doAddCarrierResponse", targetNamespace = "http://zone.tsp.com", className = "com.tsp.zone.DoAddCarrierResponse")
    @Action(input = "http://zone.tsp.com/ZoneManagerPortType/doAddCarrierRequest", output = "http://zone.tsp.com/ZoneManagerPortType/doAddCarrierResponse")
    public void doAddCarrier(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.tsp.zone.AccountState>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doListAccount", targetNamespace = "http://zone.tsp.com", className = "com.tsp.zone.DoListAccount")
    @ResponseWrapper(localName = "doListAccountResponse", targetNamespace = "http://zone.tsp.com", className = "com.tsp.zone.DoListAccountResponse")
    @Action(input = "http://zone.tsp.com/ZoneManagerPortType/doListAccountRequest", output = "http://zone.tsp.com/ZoneManagerPortType/doListAccountResponse")
    public List<AccountState> doListAccount(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.tsp.zone.CarrierState>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doListCarrier", targetNamespace = "http://zone.tsp.com", className = "com.tsp.zone.DoListCarrier")
    @ResponseWrapper(localName = "doListCarrierResponse", targetNamespace = "http://zone.tsp.com", className = "com.tsp.zone.DoListCarrierResponse")
    @Action(input = "http://zone.tsp.com/ZoneManagerPortType/doListCarrierRequest", output = "http://zone.tsp.com/ZoneManagerPortType/doListCarrierResponse")
    public List<CarrierState> doListCarrier(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doAddAccountLCR", targetNamespace = "http://zone.tsp.com", className = "com.tsp.zone.DoAddAccountLCR")
    @ResponseWrapper(localName = "doAddAccountLCRResponse", targetNamespace = "http://zone.tsp.com", className = "com.tsp.zone.DoAddAccountLCRResponse")
    @Action(input = "http://zone.tsp.com/ZoneManagerPortType/doAddAccountLCRRequest", output = "http://zone.tsp.com/ZoneManagerPortType/doAddAccountLCRResponse")
    public boolean doAddAccountLCR(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "doDeleteAccountLCR", targetNamespace = "http://zone.tsp.com", className = "com.tsp.zone.DoDeleteAccountLCR")
    @ResponseWrapper(localName = "doDeleteAccountLCRResponse", targetNamespace = "http://zone.tsp.com", className = "com.tsp.zone.DoDeleteAccountLCRResponse")
    @Action(input = "http://zone.tsp.com/ZoneManagerPortType/doDeleteAccountLCRRequest", output = "http://zone.tsp.com/ZoneManagerPortType/doDeleteAccountLCRResponse")
    public void doDeleteAccountLCR(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doUpdateMember", targetNamespace = "http://zone.tsp.com", className = "com.tsp.zone.DoUpdateMember")
    @ResponseWrapper(localName = "doUpdateMemberResponse", targetNamespace = "http://zone.tsp.com", className = "com.tsp.zone.DoUpdateMemberResponse")
    @Action(input = "http://zone.tsp.com/ZoneManagerPortType/doUpdateMemberRequest", output = "http://zone.tsp.com/ZoneManagerPortType/doUpdateMemberResponse")
    public boolean doUpdateMember(
        @WebParam(name = "arg0", targetNamespace = "")
        MemberState arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doUpdatePassword", targetNamespace = "http://zone.tsp.com", className = "com.tsp.zone.DoUpdatePassword")
    @ResponseWrapper(localName = "doUpdatePasswordResponse", targetNamespace = "http://zone.tsp.com", className = "com.tsp.zone.DoUpdatePasswordResponse")
    @Action(input = "http://zone.tsp.com/ZoneManagerPortType/doUpdatePasswordRequest", output = "http://zone.tsp.com/ZoneManagerPortType/doUpdatePasswordResponse")
    public boolean doUpdatePassword(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doUpdateBilling", targetNamespace = "http://zone.tsp.com", className = "com.tsp.zone.DoUpdateBilling")
    @ResponseWrapper(localName = "doUpdateBillingResponse", targetNamespace = "http://zone.tsp.com", className = "com.tsp.zone.DoUpdateBillingResponse")
    @Action(input = "http://zone.tsp.com/ZoneManagerPortType/doUpdateBillingRequest", output = "http://zone.tsp.com/ZoneManagerPortType/doUpdateBillingResponse")
    public boolean doUpdateBilling(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        BillingState arg1);

}
